highlighter: rouge
theme: minima
google_analytics: UA-627907-4
twitter_username: kylev
github_username: kylev
title: kylev
author: Kyle V
url: "https://kylev.github.io"
plugins:
  - jekyll-feed
  - jekyll-sitemap
